package worktree

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

func Create() (string, error) {
	baseDir := filepath.Join(os.TempDir(), "pivot-worktrees")
	if err := os.MkdirAll(baseDir, 0700); err != nil {
		return "", fmt.Errorf("create worktree base dir: %w", err)
	}

	dir, err := os.MkdirTemp(baseDir, "wt-*")
	if err != nil {
		return "", err
	}

	cmd := exec.Command("git", "worktree", "add", dir, "-b", "pivot-temp") // #nosec G204 -- executable is fixed and dir is generated by os.MkdirTemp.
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		if removeErr := os.RemoveAll(dir); removeErr != nil {
			return "", fmt.Errorf("git worktree add failed: %w (cleanup failed: %v)", err, removeErr)
		}
		return "", fmt.Errorf("git worktree add failed: %w", err)
	}

	return dir, nil
}

func Cleanup(dir string) error {
	cmd := exec.Command("git", "worktree", "remove", "--force", dir) // #nosec G204 -- executable is fixed and dir was created by this package.
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git worktree remove failed: %w", err)
	}
	return nil
}
